<?php

namespace Omnipay\IPay88\Message;

use Omnipay\Common\Message\{AbstractResponse, RequestInterface};

class CompletePurchaseResponse extends AbstractResponse
{
    private $reQueryResponse = [
        '00' => 'Successful payment',
        'Invalid parameters' => 'Parameters pass in incorrect',
        'Record not found' => 'Cannot found the record',
        'Incorrect amount' => 'Amount different',
        'Payment fail' => 'Payment fail',
        'M88Admin' => 'Payment status updated by iPay88 Admin(Fail)'
    ];

    private $invalidSignatureMsg = 'Invalid signature returned from iPay88';

    protected $message;

    protected $status = true;

    /**
     * @inheritDoc
     */
    public function __construct(RequestInterface $request, $data)
    {
        parent::__construct($request, $data);

        if ($this->data['Status'] != 1) {
            $this->message = $this->data['ErrDesc'];
            $this->status = false;
        } elseif ($this->data['Signature'] != $this->data['ComputedSignature']) {
            $this->message = $this->invalidSignatureMsg;
            $this->status = false;
        } else {
            $this->message = isset($this->data['ReQueryStatus'])
                ? ($this->reQueryResponse[$this->data['ReQueryStatus']] ?? '')
                : '';
            $this->status = '00' == $this->data['ReQueryStatus'];
        }
    }

    /**
     * @inheritDoc
     */
    public function isSuccessful(): bool
    {
        return $this->status;
    }

    /**
     * @inheritDoc
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * @inheritDoc
     */
    public function getTransactionReference()
    {
        // reference provided by the gateway to represent this transaction
        return $this->data['RefNo'];
    }

    /**
     * @inheritDoc
     */
    public function getTransactionId()
    {
        // transaction ID as generated by the merchant website
        return $this->data['TransId'];
    }
}
